services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: app_rolim_adv
    command: npm start
    ports:
      - "80:80"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - db

networks:
  db:
    driver: bridge
