import Head from "next/head";
import pdfHipo from "./pdf";
import http from "../config/http";
import useLoacalStorage from "../hooks/useLocalStorage";
import { useEffect } from "react";
import Card from "../components/Card";
import Chart from "../components/chart";
import Table from "../components/table";

export default function Dashboard() {
  const [token, setToken] = useLoacalStorage("authorization", "");
  const chartDataExample = {
    labels: ["January", "February", "March", "April", "May"],
    datasets: [
      {
        label: "Processos",
        data: [65, 59, 80, 81, 56],
        fill: false,
        borderColor: "blue",
        tension: 0.1,
      },
    ],
  };

  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container-full text-center m-5">
          <div className="row my-4">
            <div className="col mx-2">
              <Card data={"32"} cardTitle={"Clientes Ativos"} />
            </div>
            <div className="col mx-2">
              <Card data={"32"} cardTitle={"Clientes Ativos"} />
            </div>
            <div className="col mx-2">
              <Card data={"32"} cardTitle={"Clientes Ativos"} />
            </div>
            <div className="col mx-2">
              <Card data={"32"} cardTitle={"Clientes Ativos"} />
            </div>
          </div>
          <div className="row">
            <div className="col-6 mx-3">
              <Chart
                data={chartDataExample}
                title={"Processos por mês"}
                type={"line"}
              />
            </div>
            <div className="col-5 mx-3">
              <Table
                data={"test"}
                title={"Últimas atualizações"}
                columns={["ID", "Data", "Processo", "Advogado", "Atualização"]}
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
