import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import InputMask from 'react-input-mask';
import pdfHipo from './pdf';
import http from '../config/http'
import useLoacalStorage from '../hooks/useLocalStorage';
import { useEffect } from 'react';

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);

  const toggleMenu = () => {
    setIsOpen(!isOpen);
  }
  const [token, setToken] = useLoacalStorage('authorization','')

  useEffect(()=>{
    setToken("")
  },[])

  const logar = async () => {
    const res = await http.post("/api/login", {
      username: "admin",
      password: "admin"
    });
    setToken(res.jwtToken)
  }

  const testAuth = async () => {
    await http.get('/api/test');
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* NAVBAR (NAVEGAÇÃO) DA PAGINA */}
      <header>
        <nav>
          <div className='logo'>
            <Image src="/images/logo Rolim Advocacia 1 (2).png" width={140} height={70} alt="Logo" />
          </div>

          <div className={`nav-list ${isOpen ? 'open' : ''}`}>
            <ul>
              <li className='nav-item'><a href="#inicio" className='nav-link'>Inicio</a></li>
              <li className='nav-item'><a href="#historia" className='nav-link'>Nossa História</a></li>
              <li className='nav-item'><a href="#adv" className='nav-link'>Advogados</a></li>
              <li className='nav-item'><a href="#local" className='nav-link'>Como chegar</a></li>
              <li className='nav-item'><a href="#contato" className='nav-link'>Contato</a></li>
              <li><button><a href="#">Entrar</a></button></li>
            </ul>
          </div>

          <div className='login'>
            <button><a href="#">Entrar</a></button>
          </div>

          <div className='menu' onClick={toggleMenu}>
            <div className='hamburger-menu'>
              <div className='bar'></div>
              <div className='bar'></div>
              <div className='bar'></div>
            </div>
          </div>
        </nav>
      </header>

      <main>
      <button onClick={logar}>Logar</button>
        <button onClick={testAuth}>Test auth</button>
        <button onClick={() => pdfHipo(3607)}>Generate Hipo</button>

        {/* INICIO */}
        <div id='inicio' className='Div_Principal'>

        </div>

        {/* HISTÓRIA */}
        <div id='historia' className='Div_Principal'>
          <h1>Historia</h1>
          <div className="historia">
            <h2>Nossa História</h2>
            <p>Você busca por uma advocacia que entenda não só as leis, mas também a importância da proximidade e do comprometimento com seus clientes? Bem-vindo ao escritório de advocacia Rawlinson Rolim Advogados Associados, seu parceiro legal estratégico situado no coração do centro jurídico de Macaé!
            <br /><br />Localizada estrategicamente na Rua Dr. Bueno, nossa sede está a apenas 2 Km do Fórum Trabalhista e a 4 Km do Fórum da Comarca de Macaé. Essa proximidade não é apenas geográfica; é a nossa promessa de estar ao seu lado em cada passo do processo legal.
            <br /><br />Imagine uma equipe dedicada, apaixonada pela justiça e pronta para lutar pelos seus direitos. Aqui, no Rawlinson Rolim Advogados Associados, isso não é apenas uma visão - é a nossa realidade diária.
            <br /><br />Com uma vasta experiência em diversas áreas do direito, desde trabalhista até civil, estamos preparados para oferecer soluções jurídicas sob medida para as suas necessidades específicas. Não importa quão complexo seja o desafio, estamos aqui para simplificar o processo e alcançar resultados que superem suas expectativas.
            <br /><br />Não adie mais. Venha nos visitar e descubra como podemos fazer a diferença em seu caso legal. Rawlinson Rolim Advogados Associados: onde expertise encontra compromisso.
            <br />Rua Dr. Bueno, n°148 - 303, Centro - Macaé</p>
            <Image src="/images/example.png" width={300} height={200} alt="Foto da História" />
            </div>
        </div>

        {/* ADVOGADOS */}
        <div id='adv' className='Div_Principal'>
          <h1>Advogados</h1>

          <div className="advogado">
            <Image src="/images/example.png" width={100} height={100} alt="Foto do Advogado" />
            <div className="informacoes">
              <h2>Rawlinson Wagner Moraes Rolim</h2>
              <p>OAB/RJ 199.654</p>
              <p>Advogado orientado ao cliente, com histórico de liderança de equipes de alto desempenho voltadas a atingir ou superar metas. Dedicado e esforçado, com determinação em entregar excelência. Agregador de times tático, com experiência em treinamento e desenvolvimento de equipes.</p>
              <h3>Experiência Profissional</h3>
              <ul>
                <li>Elaboração de renúncias a exercício de direito, recursos e petições precisos e minuciosos em nome dos clientes.</li>
                <li>Desenvolvimento de estratégias litigiosas detalhadas para cada caso.</li>
                <li>Explanação sobre o processo jurídico a cada cliente, respondendo a perguntas para reduzir preocupações.</li>
              </ul>
            </div>
          </div>

        </div>

        {/* COMO CHEGAR */}
        <div id='local' className='Div_Principal'>
          <h1>Como Chegar</h1>
        </div>

        {/* CONTATO */}
        <div id='contato' className='Div_Principal contato'>
          <h1>Contato</h1>
          <div className="container">
            <div className="left">
              <h2>Endereço</h2>
              <p>Edificio Enedina, Rua Doutor Bueno, n°148 - 303, Centro - Macaé.</p>
              <p>Email: contato@rawlinsonrolimadv.com</p>
              <p>Telefones:</p>
              <p>(22) 99965-3649</p>
              <p>(22) 2142-6826 / (22) 99761-3980</p>
            </div>
            <div className="right">
              <h2>Contato</h2>
              <form>
                <label htmlFor="nome">Nome:</label>
                <input type="text" id="nome" name="nome" placeholder='Digite seu nome' required />
                
                <label htmlFor="email">Email:</label>
                <input type="email" id="email" name="email" placeholder='Insira seu Email' required />
                
                <label htmlFor="telefone">Telefone:</label>
                <InputMask mask="(99) 99999-9999" maskChar={null} id="telefone" name="telefone" placeholder='(DDD) XXXXX-XXXX' required />
                
                <label htmlFor="mensagem">Mensagem:</label>
                <textarea id="mensagem" name="mensagem" placeholder='Digite sua mensagem' rows={4} required></textarea>
                
                <button type="submit">Enviar</button>
              </form>
            </div>
          </div>
        </div>
      </main>

      {/* FOOTER DA PAGINA */}
      <footer>
        <div className='footer_historia'>
          <Image src="/images/logo Rolim Advocacia 1 (2).png" width={140} height={70} alt="Logo" />
          <p>Se você busca por um parceiro jurídico confiável e dedicado, não hesite em nos contatar. Rawlinson Rolim Advogados Associados está pronto para oferecer a assistência jurídica que você merece.</p>
        </div>

        <div className='footer_social_media'>
          <h1>Contatos</h1>
          <a href="#" className='footer-link'><Image src="/images/instagram_icon.png" width={45} height={45} alt="Instagram_icon" />@Instagram</a>
          <br/><br/>
          <a href="#" className='footer-link'><Image src="/images/Whatsapp_icon.png" width={40} height={40} alt="Whatsapp_icon" />(99)99999-9999</a>
        </div>

        <div className='footer_links'>
          <h1>Links</h1>
          <a href="#inicio" className='nav-link'>Inicio</a>
          <a href="#historia" className='nav-link'>Nossa História</a>
          <a href="#adv" className='nav-link'>Advogados</a>
          <a href="#local" className='nav-link'>Como chegar</a>
          <a href="#contato" className='nav-link'>Contato</a>
        </div>
      </footer>
    </div>
  );
}