import Head from 'next/head'
import LoginPage from './LoginPage'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <a href='./LoginPage'>Login</a>
      </main>
    </div>
  )
}
