import Head from 'next/head'
import { useState } from 'react'
import Image from 'next/image'

export default function LoginPage() {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [usernamePlaceholder, setUsernamePlaceholder] = useState('Usuario')
  const [passwordPlaceholder, setPasswordPlaceholder] = useState('Senha')

  const handleSubmit = (e) => {
    e.preventDefault()
    console.log('Username:', username)
    console.log('Password:', password)
  }
  // Palavra Usuario dentro do campo
  const handleUsernameChange = (e) => {
    setUsername(e.target.value)
    if (e.target.value.length > 0) {
      setUsernamePlaceholder('')
    } else {
      setUsernamePlaceholder('Usuario')
    }
  }
  // Palavra Senha dentro do campo
  const handlePasswordChange = (e) => {
    setPassword(e.target.value)
    if (e.target.value.length > 0) {
      setPasswordPlaceholder('')
    } else {
      setPasswordPlaceholder('Senha')
    }
  }

  const togglePasswordVisibility = () => {
    setShowPassword(!showPassword)
  }

  return (
    <div >
      <Head>
        <title>LoginPage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='header'>
        <a href='./'>
          <Image src="/images/logo Rolim Advocacia 1 (2).png" alt="Logo" width={150} height={70}/>
        </a>
      </header>

      <main>
        <form onSubmit={handleSubmit}> 
          <div className='inputGroup'> 
            <h1 className='LoginTitle'>Login</h1>
            <div className='input'>
              <input 
                type="text"
                id="username"
                value={username}
                onChange={handleUsernameChange}
                placeholder={usernamePlaceholder}
                maxLength={100}  // Limite de caracteres
                className='input'
                required
              />
            </div>
            <div className='input'>             
              <input
                type={showPassword ? "text" : "password"}
                id="password"
                value={password}
                onChange={handlePasswordChange}
                placeholder={passwordPlaceholder}
                className='input'
                required
              />
            </div>
            <div className='checkboxContainer'>
              <input
                type="checkbox"
                id="showPassword"
                checked={showPassword}
                onChange={togglePasswordVisibility}
              />
              <label htmlFor="showPassword">Mostrar Senha</label>
            </div>
            <button type="submit" className='buttonSubmit' >Login</button>
            <a href='./' className='buttonEsqueciSenha' >Esqueci a senha</a>
          </div>
        </form>
      </main>

      <footer className='footer'>
        <p>© 2024 RawlinsonRolimADV. Todos os direitos reservados.</p>
      </footer>
    </div>
  )
}
