import Head from 'next/head'
import { useEffect, useState } from 'react'
import useLoacalStorage from '../hooks/useLocalStorage'
import http from '../config/http'
import { toast } from 'react-toastify'
import { useRouter } from 'next/router'
import styles from '../styles/LoginPage.module.css';

export default function LoginPage() {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [token, setToken] = useLoacalStorage('authorization','')
  const [userData, setUserData] = useLoacalStorage('user_data','')
  const router = useRouter();

  useEffect(()=>{
    setToken("")
  },[])

  const login = async () => {
    try{
      const res = await http.post("/api/login", {
        username,
        password
      });
      setToken(res.jwtToken);
      setUserData(res.jwtData);
      toast.success("Usuário logado com sucesso");
      //router.push("/home")
    }catch(e){
      console.log(e);
    }
  }

  const handleUsernameChange = (e) => {
    setUsername(e.target.value)
  }

  const handlePasswordChange = (e) => {
    setPassword(e.target.value)
  }

  const togglePasswordVisibility = () => {
    setShowPassword(!showPassword)
  }

  return (
    <div >
      <Head>
        <title>LoginPage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.inputGroup}> 
          <h1 className={styles.LoginTitle}>Login</h1>
          <div className={styles.input}>
            <input 
              type="text"
              id="username"
              value={username}
              onChange={handleUsernameChange}
              placeholder="Usuario"
              maxLength={100}  // Limite de caracteres
              className={styles.input}
              required
            />
          </div>
          <div className={styles.input}>             
            <input
              type={showPassword ? "text" : "password"}
              id="password"
              value={password}
              onChange={handlePasswordChange}
              placeholder="Senha"
              className={styles.input}
              required
            />
          </div>
          <div className={styles.checkboxContainer}>
            <input
              type="checkbox"
              id="showPassword"
              checked={showPassword}
              onChange={togglePasswordVisibility}
            />
            <label htmlFor="showPassword">Mostrar Senha</label>
          </div>
          <div className="row" >
            <div className="col-sm-12 col-md-6" >
              <button onClick={login} className={`btn btn-primary ${styles.buttonSubmit}`}>Login</button>
            </div>
          </div>
          <button type="button" className={styles.buttonEsqueciSenha} onClick={() => router.push('/esqueciSenha')}>Esqueci a senha</button>
        </div>
      </main>
    </div>
  )
}
